import type { Product } from "@/types/product"

export const products: Product[] = [
  {
    id: "1",
    name: "Detergente Multiusos Profesiaaaaaonal",
    description: "Detergente concentrado para limpieza general de superficies",
    price: 25.99,
    image: "/placeholder-1k04e.png",
    category: "Detergentes",
    inStock: true,
  },
  {
    id: "2",
    name: "Desinfectante Antibacterial",
    description: "Desinfectante de amplio espectro para eliminación de gérmenes",
    price: 18.5,
    image: "/placeholder-hjlwj.png",
    category: "Desinfectantes",
    inStock: true,
  },
  {
    id: "3",
    name: "Limpiador de Vidrios Premium",
    description: "Fórmula especial para limpieza de vidrios sin rayas",
    price: 12.75,
    image: "/placeholder-htq8i.png",
    category: "Limpiadores Especializados",
    inStock: true,
  },
  {
    id: "4",
    name: "Jabón Líquido para Manos",
    description: "Jabón antibacterial suave para uso frecuente",
    price: 8.99,
    image: "/placeholder-xjy62.png",
    category: "Jabones",
    inStock: true,
  },
  {
    id: "5",
    name: "Limpiador de Pisos Concentrado",
    description: "Limpiador concentrado para todo tipo de pisos",
    price: 22.0,
    image: "/placeholder-mmnu6.png",
    category: "Limpiadores de Pisos",
    inStock: true,
  },
  {
    id: "6",
    name: "Papel Higiénico Industrial",
    description: "Rollo de papel higiénico de alta calidad para uso comercial",
    price: 45.0,
    image: "/placeholder-qhiwv.png",
    category: "Papel y Toallas",
    inStock: true,
  },
  {
    id: "7",
    name: "Toallas de Papel Absorbentes",
    description: "Toallas de papel de alta absorción para limpieza profesional",
    price: 32.5,
    image: "/placeholder-awxx1.png",
    category: "Papel y Toallas",
    inStock: true,
  },
  {
    id: "8",
    name: "Guantes de Limpieza Nitrilo",
    description: "Guantes desechables de nitrilo para protección durante la limpieza",
    price: 15.99,
    image: "/placeholder-6t5e9.png",
    category: "Equipos de Protección",
    inStock: true,
  },
]

export const categories = [
  "Todos",
  "Detergentes",
  "Desinfectantes",
  "Limpiadores Especializados",
  "Jabones",
  "Limpiadores de Pisos",
  "Papel y Toallas",
  "Equipos de Protección",
]
