-- Insertar productos iniciales de Clean Tec
INSERT INTO products (name, description, price, category, image_url, stock) VALUES
('ABRILLANTADOR DE LLANTAS CLEAN TEC 1 LT', 'Descripcion del producto', 84.24, 'Para Autos', 'public/images/cleantec-logo.png', 100),
('ABRILLANTADOR EN GALON 3.75', 'Descripcion del producto', 362.88, 'Para Autos', 'public/images/cleantec-logo.png', 100),
('ABRILLANTADOR EN GALON CLEAN TEC', 'Descripcion del producto', 375.73, 'Para Autos', 'public/images/cleantec-logo.png', 100),
('ABRILLANTADOR DE INTERIORES', 'Descripcion del producto', 102.06, 'Para Autos', 'public/images/cleantec-logo.png', 100),
('ACIDO MURIATICO EN GALON', 'Descripcion del producto', 145.15, 'Desinfectante', 'public/images/cleantec-logo.png', 100),
('ACIDO MURIATICO SULTAN 900ML', 'Descripcion del producto', 34.56, 'Desinfectante', 'public/images/cleantec-logo.png', 100),
('ACIDO TIBOR PURO', 'Descripcion del producto', 4816.38, 'Desinfectante', 'public/images/cleantec-logo.png', 100),
('AGUA PURIFICADA 40/500', 'Descripcion del producto', 136.31, 'Otros', 'public/images/cleantec-logo.png', 100),
('AJAX LIQUIDO LIMON 5LT', 'Descripcion del producto', 244.9, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('APLICADOR MULTIUSOS 2 PIEZAS', 'Descripcion del producto', 19.66, 'Otros', 'public/images/cleantec-logo.png', 100),
('ARIEL BLACK 8.5L', 'Descripcion del producto', 375.3, 'Detergente', 'public/images/cleantec-logo.png', 100),
('ARIEL PODS 3/1', 'Descripcion del producto', 466.79, 'Detergente', 'public/images/cleantec-logo.png', 100),
('ARIEL VIVID 8.5L', 'Descripcion del producto', 335.34, 'Detergente', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE AIR WICK', 'Descripcion del producto', 485.52, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE AIR WICK', 'Descripcion del producto', 460.0, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE AIR WICK COCONUT BERRIES', 'Descripcion del producto', 485.03, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE AIR WICK DURAZNO/MANGO', 'Descripcion del producto', 447.96, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE AIR WICK FLORES HAWA', 'Descripcion del producto', 455.75, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE AIR WICK PANQUE NAVIDEÑO', 'Descripcion del producto', 460.08, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE AMBIENTAL', 'Descripcion del producto', 440.64, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM 500ML DARK', 'Descripcion del producto', 196.56, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM BOUQUET 500ML', 'Descripcion del producto', 213.84, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM CARRO NUEVO', 'Descripcion del producto', 196.56, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM CEREZA', 'Descripcion del producto', 196.56, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM CHICLE', 'Descripcion del producto', 197.12, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM DRAKAR', 'Descripcion del producto', 197.12, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM HUGO', 'Descripcion del producto', 197.12, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM LIZ GARDEN', 'Descripcion del producto', 197.12, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM MANZANA CANELA', 'Descripcion del producto', 196.56, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM PIÑA MANGO', 'Descripcion del producto', 197.12, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM TROPICAL', 'Descripcion del producto', 197.12, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE ARQUIM VARIOS AROMAS 60ML', 'Descripcion del producto', 50.54, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE EN AEROSOL GLADE (PERA)', 'Descripcion del producto', 64.09, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE FEBREZE HAWAIIAN ALOHA 250G', 'Descripcion del producto', 88.8, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE FEBREZE LINEN & SKY', 'Descripcion del producto', 105.85, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE FEBREZE OCEAN', 'Descripcion del producto', 105.85, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE FRESH LEMON', 'Descripcion del producto', 105.85, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE GLADE', 'Descripcion del producto', 61.79, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE GLADE 227G', 'Descripcion del producto', 53.71, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE GLADE MERRY CHERRY', 'Descripcion del producto', 64.09, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE GLADE WINTER NIGTH', 'Descripcion del producto', 64.09, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE HUELE MACHIN', 'Descripcion del producto', 140.78, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE NICE FRESH BOUQUET', 'Descripcion del producto', 161.46, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE NICE FRESH VARIOS AROMAS', 'Descripcion del producto', 147.42, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('AROMATIZANTE LAVANDA/LIRIOS', 'Descripcion del producto', 485.03, 'Aromatizante', 'public/images/cleantec-logo.png', 100),
('ATOMIZADOR DE 1/2 LITRO', 'Descripcion del producto', 29.08, 'Otros', 'public/images/cleantec-logo.png', 100),
('ATOMIZADOR DE 1 LITRO', 'Descripcion del producto', 27.23, 'Otros', 'public/images/cleantec-logo.png', 100),
('ATOMIZADOR GRIS 1LT', 'Descripcion del producto', 68.31, 'Otros', 'public/images/cleantec-logo.png', 100),
('AWESOME 32 OZ', 'Descripcion del producto', 37.0, 'Otros', 'public/images/cleantec-logo.png', 100),
('AZUCAR REFINADA 10/1 KG ZULKA', 'Descripcion del producto', 385.32, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('BANDEJA DE HORNO OVALADA', 'Descripcion del producto', 16.21, 'Otros', 'public/images/cleantec-logo.png', 100),
('BANDEJA DE HORNO RECTANGULAR', 'Descripcion del producto', 10.15, 'Otros', 'public/images/cleantec-logo.png', 100),
('BASE CON LLANTAS', 'Descripcion del producto', 1239.84, 'Otros', 'public/images/cleantec-logo.png', 100),
('BASE METALICA 40CM', 'Descripcion del producto', 114.31, 'Otros', 'public/images/cleantec-logo.png', 100),
('BASE METALICA 60CM', 'Descripcion del producto', 127.37, 'Otros', 'public/images/cleantec-logo.png', 100),
('BASE METALICA 90CM', 'Descripcion del producto', 136.61, 'Otros', 'public/images/cleantec-logo.png', 100),
('BLANQUEADOR BLANCATEL GALON', 'Descripcion del producto', 54.95, 'Detergente', 'public/images/cleantec-logo.png', 100),
('BLANQUEADOR CLORALEX 10LT', 'Descripcion del producto', 175.81, 'Detergente', 'public/images/cleantec-logo.png', 100),
('BLANQUEADOR CLORALEX 500', 'Descripcion del producto', 9.97, 'Detergente', 'public/images/cleantec-logo.png', 100),
('BLANQUEADOR CLORALEX 950ML', 'Descripcion del producto', 19.44, 'Detergente', 'public/images/cleantec-logo.png', 100),
('BLANQUEADOR CLORALEX GALON', 'Descripcion del producto', 56.13, 'Detergente', 'public/images/cleantec-logo.png', 100),
('BLANQUEADOR CLORO AWESOME', 'Descripcion del producto', 69.53, 'Detergente', 'public/images/cleantec-logo.png', 100),
('BLANQUEADOR CLOROX 930ML', 'Descripcion del producto', 16.56, 'Detergente', 'public/images/cleantec-logo.png', 100),
('BLANQUEADOR MM 20 LITROS', 'Descripcion del producto', 288.37, 'Detergente', 'public/images/cleantec-logo.png', 100),
('BOLSA CAMISETA 500 PIEZAS', 'Descripcion del producto', 202.61, 'Otros', 'public/images/cleantec-logo.png', 100),
('BOLSA CAMISETA C/500', 'Descripcion del producto', 190.94, 'Otros', 'public/images/cleantec-logo.png', 100),
('BOLSA DE ROLLO NEGRA 55 GAL C/100', 'Descripcion del producto', 153.44, 'Bolsas', 'public/images/cleantec-logo.png', 100),
('BOLSA DE ROLLO 11X14', 'Descripcion del producto', 60.6, 'Bolsas', 'public/images/cleantec-logo.png', 100),
('BOLSA DE ROLLO 11X14', 'Descripcion del producto', 218.7, 'Bolsas', 'public/images/cleantec-logo.png', 100),
('BOLSA DE ROLLO 6X10', 'Descripcion del producto', 33.52, 'Bolsas', 'public/images/cleantec-logo.png', 100),
('BOLSA DE ROLLO 8X12', 'Descripcion del producto', 39.93, 'Bolsas', 'public/images/cleantec-logo.png', 100),
('BOLSA DE ROLLO DE 60 GALONES NEGRA', 'Descripcion del producto', 165.96, 'Bolsas', 'public/images/cleantec-logo.png', 100),
('BOLSA DE ROLLO LINEA VERDE 11X14', 'Descripcion del producto', 227.67, 'Bolsas', 'public/images/cleantec-logo.png', 100),
('BOLSA NEGRA 12/16', 'Descripcion del producto', 38.04, 'Bolsas', 'public/images/cleantec-logo.png', 100),
('BOLSA PARA BASURA 60GL NEGRA', 'Descripcion del producto', 596.6, 'Bolsas', 'public/images/cleantec-logo.png', 100),
('BOLSA PARA BASURA NEGRA 33GL', 'Descripcion del producto', 101.53, 'Bolsas', 'public/images/cleantec-logo.png', 100),
('BOTE DE PLASTICO ABIERTO O CERRADO DE 200LTS', 'Descripcion del producto', 308.88, 'Otros', 'public/images/cleantec-logo.png', 100),
('BOTE DE PLASTICO CON TAPA', 'Descripcion del producto', 240.5, 'Otros', 'public/images/cleantec-logo.png', 100),
('BOTE PARA BASURA NEGRO', 'Descripcion del producto', 101.53, 'Otros', 'public/images/cleantec-logo.png', 100),
('BOTE RUBBERMAID', 'Descripcion del producto', 1974.67, 'Otros', 'public/images/cleantec-logo.png', 100),
('BROCHES 30 PIEZAS', 'Descripcion del producto', 40.17, 'Otros', 'public/images/cleantec-logo.png', 100),
('CAFE MOLIDO FOLGERS 1.23', 'Descripcion del producto', 678.5, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('CAJA DE PLASTICO CON TAPA GRANDE', 'Descripcion del producto', 356.48, 'Otros', 'public/images/cleantec-logo.png', 100),
('CARRITO AMARILLO CON EXPRIMIDOR', 'Descripcion del producto', 1244.38, 'Otros', 'public/images/cleantec-logo.png', 100),
('CARRITO ESTANDAR PARA EL ASEO', 'Descripcion del producto', 1503.36, 'Otros', 'public/images/cleantec-logo.png', 100),
('CEPILLO CERDA SUAVE GRIS 24', 'Descripcion del producto', 310.85, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CEPILLO HD9 CALI', 'Descripcion del producto', 186.18, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CEPILLO LAVA CARRO COMPLETO', 'Descripcion del producto', 146.97, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CEPILLO NEGRO SEMIDURO "18"', 'Descripcion del producto', 277.6, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CEPILLO PARA LLANTAS HD9', 'Descripcion del producto', 22.86, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CEPILLO SANITARIO CON TAZON', 'Descripcion del producto', 39.24, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CEPILLO TIPO PLANCHA', 'Descripcion del producto', 17.96, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CERA PARA MUEBLES LEMON FURNITURE', 'Descripcion del producto', 45.36, 'Otros', 'public/images/cleantec-logo.png', 100),
('CESTO PARA BASURA', 'Descripcion del producto', 191.14, 'Otros', 'public/images/cleantec-logo.png', 100),
('CHAROLA 6X6 500 PIEZAS', 'Descripcion del producto', 491.4, 'Otros', 'public/images/cleantec-logo.png', 100),
('CHAROLA 8X8 BLANCA', 'Descripcion del producto', 203.58, 'Otros', 'public/images/cleantec-logo.png', 100),
('CHAROLA DE PLASTICO NEGRA', 'Descripcion del producto', 673.92, 'Otros', 'public/images/cleantec-logo.png', 100),
('CHAROLA TERMICA #066', 'Descripcion del producto', 220.0, 'Otros', 'public/images/cleantec-logo.png', 100),
('CHAROLA TERMICA 855', 'Descripcion del producto', 31.03, 'Otros', 'public/images/cleantec-logo.png', 100),
('CONGA 41 LITROS', 'Descripcion del producto', 401.76, 'Otros', 'public/images/cleantec-logo.png', 100),
('CONGA DE 40 LITROS CON TAPA', 'Descripcion del producto', 249.75, 'Otros', 'public/images/cleantec-logo.png', 100),
('CONGA DE 55 GALONES', 'Descripcion del producto', 484.27, 'Otros', 'public/images/cleantec-logo.png', 100),
('COTONELLE SOOM', 'Descripcion del producto', 498.15, 'Papel', 'public/images/cleantec-logo.png', 100),
('CREMA COFFE MATTE', 'Descripcion del producto', 204.83, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('CUBETA BLANCA CUADRADA', 'Descripcion del producto', 35.21, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CUBETA FLEXIBLE #10', 'Descripcion del producto', 71.85, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CUBETA FLEXIBLE #16', 'Descripcion del producto', 112.67, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CUBETA FLEXIBLE #8', 'Descripcion del producto', 37.56, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('CUBRE BOCA TRICAPA', 'Descripcion del producto', 54.14, 'Equipos de protección', 'public/images/cleantec-logo.png', 100),
('CUCHARA CAFETERA', 'Descripcion del producto', 16.17, 'Otros', 'public/images/cleantec-logo.png', 100),
('CUCHARA PRIME LINE PAQUETE CON 100', 'Descripcion del producto', 177.61, 'Otros', 'public/images/cleantec-logo.png', 100),
('DESENGRASANTE AWESOME 128OZ', 'Descripcion del producto', 125.43, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('DESENGRASANTE CAFE INDUSTRIAL 1LTS', 'Descripcion del producto', 60.48, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('DESENGRASANTE CONCENTRADO', 'Descripcion del producto', 953.04, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('DESENGRASANTE CONCENTRADO GALON HEAVY DUTY', 'Descripcion del producto', 129.47, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('DESENGRASANTE CONCENTRADO MM 10L', 'Descripcion del producto', 357.75, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('DESENGRASANTE MULTIUSOS REAL CELAN 10 LT', 'Descripcion del producto', 369.7, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('DESENGRASANTE POWEROSO 946ML', 'Descripcion del producto', 34.88, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('DESENGRASANTE QUICK POWER 1LTS', 'Descripcion del producto', 45.36, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('DESENGRASANTE REAL CLEAN 20LTS', 'Descripcion del producto', 939.6, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('DESPACAHDOR DE HIGIENICO JR', 'Descripcion del producto', 326.59, 'Otros', 'public/images/cleantec-logo.png', 100),
('DESPACHADOR PARA TOALLA INTERDOBLADA', 'Descripcion del producto', 331.7, 'Otros', 'public/images/cleantec-logo.png', 100),
('DESPACAÑOS PALMA', 'Descripcion del producto', 34.29, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('DETERGENTE ACE', 'Descripcion del producto', 393.86, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE ARIEL 500GR', 'Descripcion del producto', 26.24, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE DOWNY', 'Descripcion del producto', 370.12, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE DOWNY BOTANICALS FRUITY', 'Descripcion del producto', 306.18, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE DOWNY CONCENTRADO', 'Descripcion del producto', 352.18, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE EN POLVO ARCOIRIS 9KG', 'Descripcion del producto', 289.48, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE EN POLVO FOCA 250GR', 'Descripcion del producto', 12.0, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE EN POLVO FOCA 500G', 'Descripcion del producto', 22.41, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE EN POLVO GREAT VALUE 5KG', 'Descripcion del producto', 120.96, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE EN POLVO MAESTRO LIMPIO', 'Descripcion del producto', 362.6, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE EN POLVO ROMA 10KG', 'Descripcion del producto', 427.04, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE EN POLVO ROMA 1KG', 'Descripcion del producto', 55.76, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE EN POLVO BLANCA NIEVES 1KG', 'Descripcion del producto', 42.4, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE FOCA 1KG', 'Descripcion del producto', 42.48, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO CARISMA 500ML', 'Descripcion del producto', 18.52, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO ARCOIRIS 1L', 'Descripcion del producto', 31.32, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO ACROIRIS PARA TODO TIPO DE ROPA', 'Descripcion del producto', 28.43, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO ARCOIRIS ROPA OSCURA', 'Descripcion del producto', 25.22, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO ARIEL 8.5LT', 'Descripcion del producto', 448.77, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO BLANCA NIEVES', 'Descripcion del producto', 18.52, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO CARISMA', 'Descripcion del producto', 42.12, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO COLOR Y BLANCOS', 'Descripcion del producto', 320.85, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO FOCA 1LT', 'Descripcion del producto', 47.39, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO FOCA 3.75', 'Descripcion del producto', 147.8, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO FOCA 500ML', 'Descripcion del producto', 18.52, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO FOCA 8LTS', 'Descripcion del producto', 369.07, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO MAS COLOR BCO 9L', 'Descripcion del producto', 397.25, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO ROMA', 'Descripcion del producto', 18.52, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE LIQUIDO ROMA 1LITRO', 'Descripcion del producto', 42.58, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE ROPA DE COLOR MM 20L', 'Descripcion del producto', 614.95, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DETERGENTE SUAVITEL COMPLETE 8.5LT', 'Descripcion del producto', 361.35, 'Detergente', 'public/images/cleantec-logo.png', 100),
('DISPENSADOR DE TOALLA', 'Descripcion del producto', 476.93, 'Otros', 'public/images/cleantec-logo.png', 100),
('ELIMINADOR DE OLORES ODOBAN', 'Descripcion del producto', 212.42, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('ENCENDEDOR BIC 15 PIEZAS', 'Descripcion del producto', 20.21, 'Otros', 'public/images/cleantec-logo.png', 100),
('ENDULZANTE ESPLENDA 600 PIEZAS', 'Descripcion del producto', 356.65, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('ENSUEÑO 9LT', 'Descripcion del producto', 339.85, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('ENSUEÑO FRESCURA AZUL 740ML', 'Descripcion del producto', 28.47, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('ENSUEÑO ULTRA 740ML FRESCO VERANO', 'Descripcion del producto', 28.47, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('ESCOBA MARIEL MEDIANA', 'Descripcion del producto', 41.97, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('ESPONJA LAVA TRASTES SCOTH BRITE', 'Descripcion del producto', 25.27, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('ESPONJA MULTIUSOS CLOROX', 'Descripcion del producto', 15.88, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('ESPONJA MULTIUSOS COLORES', 'Descripcion del producto', 17.96, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('ESTROPAJO GALVANIZADO CHICO', 'Descripcion del producto', 7.83, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('ESTROPAJO GALVANIZADO GRANDE', 'Descripcion del producto', 11.91, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('FABULOSO BRISA PRIMAVERAL 2L', 'Descripcion del producto', 54.0, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('FABULOSO COLECCION ZEN 10L', 'Descripcion del producto', 308.88, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('FABULOSO MAR FRESCO 12', 'Descripcion del producto', 35.71, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('FIBRA ESPIRAL', 'Descripcion del producto', 4.81, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('FIBRA ESPIRAL GR50', 'Descripcion del producto', 17.63, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('FIBRA ESPONJA CLOROX', 'Descripcion del producto', 20.67, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('FIBRA VERDE CON ESPONJA', 'Descripcion del producto', 7.67, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('FIBRA VERDE SCOTCH BRITE P96', 'Descripcion del producto', 20.7, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('FILMICO 5 PULGADOS', 'Descripcion del producto', 87.07, 'Otros', 'public/images/cleantec-logo.png', 100),
('FLEJE ANCHO 5"60', 'Descripcion del producto', 120.46, 'Otros', 'public/images/cleantec-logo.png', 100),
('FOCA LIQUIDO 4.3 LITROS', 'Descripcion del producto', 152.89, 'Detergente', 'public/images/cleantec-logo.png', 100),
('GARRAFA DE JABON PARA MANOS', 'Descripcion del producto', 287.57, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('GATORADE LIMA LIMON 2.168', 'Descripcion del producto', 465.29, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('GATORADE SABOR NARANJA 2.38KG', 'Descripcion del producto', 423.52, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('GRILL & OVEN AWESOME', 'Descripcion del producto', 47.25, 'Otros', 'public/images/cleantec-logo.png', 100),
('GUANTE DE LATEX 100 PIEZAS', 'Descripcion del producto', 89.94, 'Equipos de protección', 'public/images/cleantec-logo.png', 100),
('GUANTE DE NITRILE', 'Descripcion del producto', 119.09, 'Equipos de protección', 'public/images/cleantec-logo.png', 100),
('GUANTE DE NITRILL TALLA L', 'Descripcion del producto', 155.25, 'Equipos de protección', 'public/images/cleantec-logo.png', 100),
('GUANTE DOMESTICO L', 'Descripcion del producto', 27.08, 'Equipos de protección', 'public/images/cleantec-logo.png', 100),
('GUANTE DOMESTICO LILA', 'Descripcion del producto', 36.63, 'Equipos de protección', 'public/images/cleantec-logo.png', 100),
('GUANTE DOMESTICO M', 'Descripcion del producto', 27.7, 'Equipos de protección', 'public/images/cleantec-logo.png', 100),
('GUANTE DOMESTICO TALLA S', 'Descripcion del producto', 29.39, 'Equipos de protección', 'public/images/cleantec-logo.png', 100),
('GUANTE DOMESTICO XL', 'Descripcion del producto', 27.08, 'Equipos de protección', 'public/images/cleantec-logo.png', 100),
('HAND SOAP JABON LIQUIDO PARA MANOS', 'Descripcion del producto', 179.33, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('HARPIC 750ML', 'Descripcion del producto', 61.51, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON AXION 1.1L AVENA VITAMINA', 'Descripcion del producto', 66.15, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON AXION 1.1L SWEET MELON', 'Descripcion del producto', 66.15, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON DAWN 3.78L', 'Descripcion del producto', 440.72, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON LIQUIDO AXION 2.8 TRICLORO', 'Descripcion del producto', 168.83, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON LIQUIDO AXION 400ML', 'Descripcion del producto', 20.93, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON LIQUIDO AXION LIMON 2.8', 'Descripcion del producto', 169.83, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON LIQUIDO PARA MANOS BEAUTY SOFT 2L', 'Descripcion del producto', 92.66, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON LIQUIDO PARA MANOS DIFERENTES AROMAS', 'Descripcion del producto', 69.39, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON LIQUIDO PARA TRASTES DAWN 2.6', 'Descripcion del producto', 262.42, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON LIQUIDO PARA TRASTES KIRKLAND 2.66L', 'Descripcion del producto', 263.84, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON LIQUIDO PARA SALVO 2.6L', 'Descripcion del producto', 184.81, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON ZOTE 200GRS', 'Descripcion del producto', 15.01, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABON ZOTE 400GRS', 'Descripcion del producto', 29.82, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABONERA', 'Descripcion del producto', 377.14, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('JABONERA CALI 1L', 'Descripcion del producto', 267.9, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FLASH BRISA MARINA 1L', 'Descripcion del producto', 22.3, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIA VIDRIOS PARA CARRO', 'Descripcion del producto', 65.32, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIA VIDRIOS POWEROSO 946ML', 'Descripcion del producto', 37.44, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FABULOSO MAR FRESCO 2L', 'Descripcion del producto', 54.0, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR BRISA MARINA MM 10 LTS', 'Descripcion del producto', 200.15, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR CLEAN TEC 1 LITRO', 'Descripcion del producto', 13.24, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FABULOSO 2L LAVANDA', 'Descripcion del producto', 54.0, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FABULOSO DE 10 LTS', 'Descripcion del producto', 279.45, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FABULOSO JAMAICA MANDARINA', 'Descripcion del producto', 327.4, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FABULOSO MENTA 10LT', 'Descripcion del producto', 353.75, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FABULOSO VARIOS AROMAS', 'Descripcion del producto', 30.1, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FLASH BRISA MARINA', 'Descripcion del producto', 21.98, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FLASH FLORAL 1L', 'Descripcion del producto', 21.01, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FLASH LAVANDA 1.25', 'Descripcion del producto', 26.37, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR FLASH LAVANDA 1L', 'Descripcion del producto', 22.3, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR LYSOL 5L', 'Descripcion del producto', 184.68, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR MM 10 LTS CITRUS', 'Descripcion del producto', 189.06, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR MM LAVANDA 10LT', 'Descripcion del producto', 244.38, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR MM LAVANDA 20 LTS', 'Descripcion del producto', 371.9, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR MM MANZANA CANELA 10LT', 'Descripcion del producto', 189.06, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR MULTIUSOS MAESTRO LIMPIO VARIOS AROMAS', 'Descripcion del producto', 256.35, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR PINOL 1LT', 'Descripcion del producto', 32.6, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR PINOL EL ORIGINAL 9LT', 'Descripcion del producto', 292.9, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR PINOL 3.75ML', 'Descripcion del producto', 123.52, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR PINOL FLORAL', 'Descripcion del producto', 260.02, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR PINOL REPELENTE 9LT', 'Descripcion del producto', 260.02, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR POETT 9L ALEGRA TU VIDA', 'Descripcion del producto', 177.19, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR POETT ALEGRA TU VIDA', 'Descripcion del producto', 20.71, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR POETT DE LAVANDA', 'Descripcion del producto', 20.71, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LIMPIADOR POETT SUAVIDAD DE ALGODON', 'Descripcion del producto', 20.71, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LYSOL AEROSOL DESINFECTANTE 354G', 'Descripcion del producto', 121.01, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LYSOL AEROSOL DESINFECTANTE 475G', 'Descripcion del producto', 150.76, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LYSOL LIMPIADOR 6LTS', 'Descripcion del producto', 201.94, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LYSOL QUITA SARRO', 'Descripcion del producto', 59.93, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LYSOL WIPES DESINFECTANTES', 'Descripcion del producto', 133.83, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('LYSOL WIPES DESINFECTANTES LEMON', 'Descripcion del producto', 133.83, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('MAGITELES EN ROLLO', 'Descripcion del producto', 47.25, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('MANGO DE MADERA CON HERRAJE DE PLASTICO', 'Descripcion del producto', 139.22, 'Otros', 'public/images/cleantec-logo.png', 100),
('MANGO PUNTA DE METAL "54', 'Descripcion del producto', 59.14, 'Otros', 'public/images/cleantec-logo.png', 100),
('MAS COLOR 4.8L', 'Descripcion del producto', 196.26, 'Detergente', 'public/images/cleantec-logo.png', 100),
('MAS COLOR PERFUME Y RENOVACION', 'Descripcion del producto', 432.25, 'Detergente', 'public/images/cleantec-logo.png', 100),
('MAS OSCURA 4.8L', 'Descripcion del producto', 197.94, 'Detergente', 'public/images/cleantec-logo.png', 100),
('MAS OSCURA 9L', 'Descripcion del producto', 443.39, 'Detergente', 'public/images/cleantec-logo.png', 100),
('MR CLEAN MAGIC ERASER', 'Descripcion del producto', 292.48, 'Detergente', 'public/images/cleantec-logo.png', 100),
('OXI CLEAN QUITA MANCHAS', 'Descripcion del producto', 191.81, 'Detergente', 'public/images/cleantec-logo.png', 100),
('PAÑALES PARA PERRO', 'Descripcion del producto', 495.0, 'Otros', 'public/images/cleantec-logo.png', 100),
('PAPEL COTONELLE SOFT', 'Descripcion del producto', 446.04, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL COTTONELLE 30 ROLLOS', 'Descripcion del producto', 225.45, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL COTTONELLE BLOSOOM 32', 'Descripcion del producto', 404.46, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL HIGIENICO DALIA 180', 'Descripcion del producto', 37.31, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL HIGIENICO DALIA 360', 'Descripcion del producto', 72.62, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL HIGIENICO JR KC C/12 200MTS', 'Descripcion del producto', 36.03, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL HIGIENICO JUMBO C/6', 'Descripcion del producto', 69.28, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL HIGIENICO KIRKLAND', 'Descripcion del producto', 112.32, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL HIGIENICO PETALO C/40', 'Descripcion del producto', 375.58, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL HIGIENICO QUALITY', 'Descripcion del producto', 9.76, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL HIGIENICO QUALITY 400 HD 12/4', 'Descripcion del producto', 38.77, 'Papel', 'public/images/cleantec-logo.png', 100),
('PAPEL HIGIENICO QUALITY 600 HD 12/4', 'Descripcion del producto', 53.62, 'Papel', 'public/images/cleantec-logo.png', 100),
('PASTILLA WIESE', 'Descripcion del producto', 13.33, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('PASTILLAS HARPIC 16', 'Descripcion del producto', 277.6, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('PASTILLAS PATO 1/6', 'Descripcion del producto', 151.63, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('PERLAS DOWNY PARADISE', 'Descripcion del producto', 367.5, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('PERLAS PARA ROPA DOWNY 141G', 'Descripcion del producto', 104.98, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('PIEDRA PARA PLANCHA GRILL', 'Descripcion del producto', 72.0, 'Otros', 'public/images/cleantec-logo.png', 100),
('PILAS DURACELL', 'Descripcion del producto', 622.24, 'Otros', 'public/images/cleantec-logo.png', 100),
('PLATO POZOLERO 20/25', 'Descripcion del producto', 25.45, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('PLATO POZOLERO C/500 PIEZAS', 'Descripcion del producto', 447.12, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('PLATO REYMA CON DIVI/ SIN DIV', 'Descripcion del producto', 551.3, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('PLEDGE LEMON 403G', 'Descripcion del producto', 101.09, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('PLUMERO DE AVESTRUZ CHICO', 'Descripcion del producto', 246.58, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('POLIFIBRAS MEXICANAS', 'Descripcion del producto', 8.7, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('POPOTE ESTUCHADO', 'Descripcion del producto', 84.24, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('POWER HOUSE FURNITURE POLISH', 'Descripcion del producto', 45.36, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('QUICK POWER 20LTS', 'Descripcion del producto', 810.0, 'Otros', 'public/images/cleantec-logo.png', 100),
('RECOGEDOR DE LAMINA CHICO', 'Descripcion del producto', 45.72, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('RECOGEDOR DE LAMINA GRANDE', 'Descripcion del producto', 57.46, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('RECOGEDOR DE LAMINA MEDIANO', 'Descripcion del producto', 57.15, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('REFUERZO PARA CEPILLO', 'Descripcion del producto', 60.42, 'Otros', 'public/images/cleantec-logo.png', 100),
('REPUESTO PARA MOP 40 BLANCO', 'Descripcion del producto', 39.19, 'Otros', 'public/images/cleantec-logo.png', 100),
('REPUESTO PARA MOP 60CM AZUL', 'Descripcion del producto', 84.91, 'Otros', 'public/images/cleantec-logo.png', 100),
('REPUESTO PARA MOP AZUL 40CM', 'Descripcion del producto', 63.5, 'Otros', 'public/images/cleantec-logo.png', 100),
('REPUESTO PARA MOP AZUL 90CM', 'Descripcion del producto', 112.67, 'Otros', 'public/images/cleantec-logo.png', 100),
('REPUESTO PARA TRAPEADOR ALGODON 40', 'Descripcion del producto', 45.36, 'Otros', 'public/images/cleantec-logo.png', 100),
('REPUESTO PARA TRAPEADOR AZUL', 'Descripcion del producto', 62.73, 'Otros', 'public/images/cleantec-logo.png', 100),
('RESMA DE HOJA BLANCAS', 'Descripcion del producto', 189.0, 'Otros', 'public/images/cleantec-logo.png', 100),
('SANITAS TOALLA INTERDOBLADA 20', 'Descripcion del producto', 19.6, 'Papel', 'public/images/cleantec-logo.png', 100),
('SCRUB FREE OXI CLEAN', 'Descripcion del producto', 45.36, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('SERVILLETA KLENEX 300 PIEZAS', 'Descripcion del producto', 51.52, 'Papel', 'public/images/cleantec-logo.png', 100),
('SERVILLETA RESTAURANT 1/500', 'Descripcion del producto', 50.91, 'Papel', 'public/images/cleantec-logo.png', 100),
('SERVILLETAS 4/260 KIRKLAND SIGNATURE', 'Descripcion del producto', 333.99, 'Papel', 'public/images/cleantec-logo.png', 100),
('SERVITOALLA INTERDOBLADA PETALO 24/250', 'Descripcion del producto', 22.65, 'Papel', 'public/images/cleantec-logo.png', 100),
('SHAMPOO PARA CARROS 1LT', 'Descripcion del producto', 41.28, 'Para Autos', 'public/images/cleantec-logo.png', 100),
('SHAMPOO PLUS AUTOMOTRIZ', 'Descripcion del producto', 37.8, 'Para Autos', 'public/images/cleantec-logo.png', 100),
('SUAVIZANTE ENSUEÑO 12/850', 'Descripcion del producto', 23.95, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVIZANTE ENSUEÑO 9L', 'Descripcion del producto', 328.92, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVITEL FRESCA PRIMAVERA 8.5', 'Descripcion del producto', 360.14, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVITEL FRESCO AROMA DE SOL', 'Descripcion del producto', 102.38, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVITEL LILA 8.5L', 'Descripcion del producto', 351.0, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVITEL MM ABRAZO DE AMOR 2.8L', 'Descripcion del producto', 119.23, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVITEL MM CARICIA IRRESISTIBLE', 'Descripcion del producto', 119.23, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVITEL UNIQUED TOUCH', 'Descripcion del producto', 386.71, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVIZANTE DE TELAS CARISMA 500ML', 'Descripcion del producto', 18.52, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVIZANTE ENSUEÑO 2.8L', 'Descripcion del producto', 81.65, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVIZANTE MM 20L', 'Descripcion del producto', 513.76, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVIZANTE SUAVITEL BABY 3L', 'Descripcion del producto', 102.38, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUAVIZANTE SUAVITEL MANZANA 3L', 'Descripcion del producto', 102.38, 'Suavizante', 'public/images/cleantec-logo.png', 100),
('SUERO ELECTROLIT 12/625', 'Descripcion del producto', 234.76, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('SUPER TELA MAGITEL', 'Descripcion del producto', 7.02, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('TAPA CON RANURA DART', 'Descripcion del producto', 78.86, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('TAPA DE 2OZ', 'Descripcion del producto', 607.66, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('TAPA PARA VASO 24EU', 'Descripcion del producto', 693.66, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('TAPETE LISTO PARA MIGITORIO', 'Descripcion del producto', 30.06, 'Otros', 'public/images/cleantec-logo.png', 100),
('TAPETE PARA MIGITORIO', 'Descripcion del producto', 14.26, 'Otros', 'public/images/cleantec-logo.png', 100),
('TENEDOR MEDIANO PAQUETE CON 100', 'Descripcion del producto', 16.12, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('TOALLA DE COCINA ADORABLE C/50 HD C/24', 'Descripcion del producto', 18.01, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA DE MICROFIBRA AZUL', 'Descripcion del producto', 12.96, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA DE MICROFIBRA KIRKLAND', 'Descripcion del producto', 14.67, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA DE ROLLO BCO C/12', 'Descripcion del producto', 50.39, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA DE ROLLO BCOTR350', 'Descripcion del producto', 61.14, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA DE ROLLO CAFE C/12', 'Descripcion del producto', 50.35, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA DE ROLLO CAFE C350', 'Descripcion del producto', 56.33, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA DE ROLLO CAFE K160', 'Descripcion del producto', 71.03, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA DE ROLLO KIRKLAND', 'Descripcion del producto', 59.09, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA DE ROLLO PARA COCINA REGIO', 'Descripcion del producto', 38.68, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA DE ROLLO SCOTT', 'Descripcion del producto', 57.86, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA INTERDOBLADA C250', 'Descripcion del producto', 40.32, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA INTERDOBLADA BLANCA TI 250', 'Descripcion del producto', 39.61, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLA PARA SECADORA SUAVITEL', 'Descripcion del producto', 38.88, 'Papel', 'public/images/cleantec-logo.png', 100),
('TOALLAS PARA SECADORA BOUNCE', 'Descripcion del producto', 444.7, 'Papel', 'public/images/cleantec-logo.png', 100),
('TRAPEADOR ALGODON AMARILLO #900', 'Descripcion del producto', 88.19, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('TRAPEADOR DE ALGODON #1000 NARANJA', 'Descripcion del producto', 101.68, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('TRAPEADOR DE ALGODON ECO AZUL #500', 'Descripcion del producto', 69.29, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('TRAPEADOR DE ALGODON ROJO #700', 'Descripcion del producto', 78.87, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('TRAPEADOR DE HILAZA COLOR 450GR', 'Descripcion del producto', 65.37, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('TRAPEADOR DE MAGITEL', 'Descripcion del producto', 32.29, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('TRAPEADOR DE MICROFIBRA GRANDE', 'Descripcion del producto', 94.04, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('TRAPEADOR DE MICROFIBRA MEDIANO', 'Descripcion del producto', 78.0, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('TRATAMIENTO BASE AGUA PISO GALON', 'Descripcion del producto', 209.95, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('ULTIMATE HOME LINT ROLLE', 'Descripcion del producto', 40.5, 'Limpieza', 'public/images/cleantec-logo.png', 100),
('VANISH BCO 9LT', 'Descripcion del producto', 370.66, 'Detergente', 'public/images/cleantec-logo.png', 100),
('VANISH OXI ACTION 120G', 'Descripcion del producto', 23.98, 'Detergente', 'public/images/cleantec-logo.png', 100),
('VANISH ROSA 9L', 'Descripcion del producto', 299.05, 'Detergente', 'public/images/cleantec-logo.png', 100),
('VASO DART 16OZ', 'Descripcion del producto', 1331.15, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('VASO DE FOAM 32 OZ 20/15', 'Descripcion del producto', 34.3, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('VASO DE FOAM DE 10 OZ 40/25PZ', 'Descripcion del producto', 17.98, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('VASO DE PLASTICO EU 24OZ REYMA', 'Descripcion del producto', 916.09, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('VASO N.10 TERMICO REYMA 40/25 PIEZAS', 'Descripcion del producto', 14.38, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('VASO N.12 TERMICO REYMA', 'Descripcion del producto', 14.53, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('VASO REYMA #8 DE PLASTICO', 'Descripcion del producto', 635.3, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('VASO REYMA FOAM #14', 'Descripcion del producto', 459.17, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('VASO REYMA FOAM #16', 'Descripcion del producto', 516.47, 'Alimentos', 'public/images/cleantec-logo.png', 100),
('WINDEX DE GALON', 'Descripcion del producto', 51.84, 'Limpieza', 'public/images/cleantec-logo.png', 100);